---
volumes:
  redisdb: {}

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "16m"
    max-file: "2"
    compress: "true"

services:
  customresponses:
    container_name: customresponses
    hostname: customresponses
    logging: *default-logging
    image: aorith/customresponses:latest
    command: python -m uvicorn customresponses.main:app --host 0.0.0.0 --port 7678
    ports:
      - 127.0.0.1:7678:7678
    depends_on:
      redis:
        condition: service_healthy

  redis:
    restart: on-failure
    container_name: redis
    hostname: redis
    image: redis:7-alpine
    entrypoint: /usr/bin/env
    command: redis-server --save 60 1 --loglevel warning
    logging: *default-logging
    volumes:
      - redisdb:/data
    healthcheck:
      test: ["CMD", "/usr/local/bin/redis-cli", "ping"]
      interval: 30s
      timeout: 3s
    deploy:
      resources:
        limits:
          memory: 375M
        reservations:
          memory: 250M
