name: build_and_push

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          cache-from: aorith:customresponses:latest
          build-args: |
            CURRENT_VERSION_REF=${{ github.ref_name }}
          context: "{{defaultContext}}:."
          file: "Dockerfile"
          push: true
          tags: aorith/customresponses:latest
